"""Import official hourly MSL tables; offline maintenance, not a runtime dependency.

Requires pypdf. Pass the two PDFs linked from hydro.navy.mi.th/waterlaveltable:
python scripts/import-navy-tides.py MK2026mls.pdf TC2026msl.pdf
"""
import calendar
import hashlib
import json
import re
import sys
from pathlib import Path
from pypdf import PdfReader

ROOT = Path(__file__).resolve().parents[1]
STATIONS = [
    ("mae-klong", "ปากน้ำแม่กลอง", "Pak Nam Mae Klong", 13 + 22/60 + 39/3600,
     99 + 59/60 + 34/3600, "https://hydro.navy.mi.th/storage/frontend/article/23009/file/th/MK2026mls.pdf"),
    ("tha-chin", "ปากน้ำท่าจีน", "Pak Nam Tha Chin", None, None,
     "https://hydro.navy.mi.th/storage/frontend/article/23007/file/th/TC2026msl.pdf"),
]
MONTHS = list(calendar.month_name)[1:]

def extract(path, spec):
    code, name, english, lat, lon, url = spec
    pages = [p.extract_text(extraction_mode="layout") for p in PdfReader(path).pages]
    notes = " ".join(pages)
    assert "Thailand standard time" in notes and "7 hours ahead" in notes
    days = {}
    for month, month_name in enumerate(MONTHS, 1):
        matches = [p for p in pages if f"{month_name} 2026" in p]
        assert len(matches) == 1, (code, month, "missing/ambiguous month")
        page = matches[0]
        assert english in page and "ABOVE MEAN SEA LEVEL" in page
        # Coordinates are published on every monthly station table.
        coords = re.findall(r'(?:Lat|Long)\)\s*(\d+)\s*[^\d\s]*\s*(\d+)\s*\'\s*(\d+)\s*"', page)
        assert len(coords) == 2, (code, "coordinates")
        values = [int(d) + int(m)/60 + int(s)/3600 for d,m,s in coords]
        if lat is None:
            lat, lon = values
        assert abs(lat-values[0]) < 1e-6 and abs(lon-values[1]) < 1e-6
        found = {}
        for line in page.splitlines():
            tokens = line.strip().split()
            if len(tokens) != 25 or not tokens[0].isdigit():
                continue
            if not all(re.fullmatch(r"-?\d+\.\d", x) for x in tokens[1:]):
                continue
            day = int(tokens[0])
            assert day not in found and 1 <= day <= calendar.monthrange(2026, month)[1]
            levels = [float(v) for v in tokens[1:]]
            assert all(-10 < v < 10 for v in levels)
            found[day] = levels
        assert set(found) == set(range(1, calendar.monthrange(2026, month)[1]+1)), (code, month, "incomplete rows")
        for day, levels in sorted(found.items()):
            days[f"2026-{month:02}-{day:02}"] = levels
    assert len(days) == 365
    return dict(id=code, name=name, lat=lat, lon=lon, year=2026, datum="msl",
                timezone="Asia/Bangkok", kind="prediction", sourceUrl=url,
                pdfSha256=hashlib.sha256(Path(path).read_bytes()).hexdigest(), days=days)

if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit("Pass Mae Klong MSL PDF and Tha Chin MSL PDF, in that order")
    tables = [extract(path, spec) for path, spec in zip(sys.argv[1:], STATIONS)]
    output = ROOT / "assets/tide-tables-2026.js"
    output.write_text("// Official Royal Thai Navy hourly predictions; MSL, Thailand time.\n"
                      "// Generated by scripts/import-navy-tides.py; do not edit readings by hand.\n"
                      "export default " + json.dumps(tables, ensure_ascii=False, separators=(",", ":")) + ";\n")
    print(f"Validated {sum(len(t['days'])*24 for t in tables)} hourly predictions in {output.name}")
